delete from image;
delete from user_known_images;
delete from user_tried_images;

drop Table image;
drop Table user_known_images;
drop Table user_tried_images;

CREATE TABLE IF NOT EXISTS image (
 image text NOT NULL PRIMARY KEY,
 word text NOT NULL,
 num int NOT NULL
);

CREATE TABLE IF NOT EXISTS hands (
 word text NOT NULL PRIMARY KEY,
 num int NOT NULL
);


CREATE TABLE IF NOT EXISTS user_known_images (
 record text NOT NULL,
 username text NOT NULL,
 image text NOT NULL,
 FOREIGN KEY(image) REFERENCES image(image),
 PRIMARY KEY (username, image)
);

CREATE TABLE IF NOT EXISTS user_tried_images (
 username text NOT NULL,
 image text NOT NULL,
 FOREIGN KEY(image) REFERENCES image(image),
 PRIMARY KEY (username, image)
);

/* 1 = easy: 3 to 4 letters, 2 = average: 5 to 6 letters, 3 = hard: more than 6 letters*/

insert into image values ("acorn.png", "acorn", 2);
insert into image values ("ant.png", "ant", 1);
insert into image values ("apple.png", "apple", 2);
insert into image values ("arm.png", "arm", 1);
insert into image values ("backpack.png", "backpack", 3);
insert into image values ("banana.png", "banana", 2);
insert into image values ("basket.png", "basket", 2);
insert into image values ("bathtub.png", "bathtub", 3);
insert into image values ("bed.png", "bed", 1);
insert into image values ("bee.png", "bee", 1);
insert into image values ("bird.png", "bird", 1);
insert into image values ("boat.png", "boat", 1);
insert into image values ("books.png", "books", 2);
insert into image values ("boots.png", "boots", 2);
insert into image values ("brain.png", "brain", 2);
insert into image values ("bread.png", "bread", 2);
insert into image values ("bridge.png", "bridge", 2);
insert into image values ("broom.png", "broom", 2);
insert into image values ("brush.png", "brush", 2);
insert into image values ("bucket.png", "bucket", 2);
insert into image values ("buttons.png", "buttons", 3);
insert into image values ("cake.png", "cake", 1);
insert into image values ("camel.png", "camel", 2);
insert into image values ("camera.png", "camera", 2);
insert into image values ("cardboardbox.png", "cardboardbox", 3);
insert into image values ("carriage.png", "carriage", 3);
insert into image values ("cart.png", "cart", 1);
insert into image values ("cat.png", "cat", 1);
insert into image values ("cheese.png", "cheese", 2);
insert into image values ("chicken.png", "chicken", 3);
insert into image values ("cherries.png", "cherries", 3);
insert into image values ("clock.png", "clock", 2);
insert into image values ("coffee.png", "coffee", 2);
insert into image values ("comb.png", "comb", 1);
insert into image values ("cow.png", "cow", 1);
insert into image values ("crocodile.png", "crocodile", 3);
insert into image values ("desk.png", "desk", 1);
insert into image values ("deer.png", "deer", 1);
insert into image values ("diamond.png", "diamond", 3);
insert into image values ("dog.png", "dog", 1);
insert into image values ("donkey.png", "donkey", 3);
insert into image values ("door.png", "door", 1);
insert into image values ("drawer.png", "drawer", 2);
insert into image values ("dress.png", "dress", 2);
insert into image values ("ear.png", "ear", 1);
insert into image values ("egg.png", "egg", 1);
insert into image values ("eye.png", "eye", 1);
insert into image values ("feather.png", "feather", 3);
insert into image values ("fish.png", "fish", 1);
insert into image values ("flag.png", "flag", 1);
insert into image values ("fly.png", "fly", 1);
insert into image values ("foot.png", "foot", 1);
insert into image values ("fork.png", "fork", 1);
insert into image values ("fruits.png", "fruits", 2);
insert into image values ("geese.png", "geese", 2);
insert into image values ("giraffe.png", "giraffe", 3);
insert into image values ("glove.png", "glove", 2);
insert into image values ("gnome.png", "gnome", 2);
insert into image values ("hammer.png", "hammer", 2);
insert into image values ("hanger.png", "hanger", 2);
insert into image values ("hare.png", "hare", 1);
insert into image values ("hats.png", "hats", 1);
insert into image values ("heart.png", "heart", 2);
insert into image values ("horn.png", "horn", 1);
insert into image values ("house.png", "house", 2);
insert into image values ("horse.png", "horse", 2);
insert into image values ("kettle.png", "kettle", 2);
insert into image values ("key.png", "key", 1);
insert into image values ("leaf.png", "leaf", 1);
insert into image values ("lemon.png", "lemon", 2);
insert into image values ("lightbulb.png", "lightbulb", 3);
insert into image values ("map.png", "map", 1);
insert into image values ("match.png", "match", 2);
insert into image values ("mice.png", "mice", 1);
insert into image values ("microwave.png", "microwave", 3);
insert into image values ("monkey.png", "monkey", 2);
insert into image values ("moon.png", "moon", 1);
insert into image values ("mouse.png", "mouse", 2);
insert into image values ("nail.png", "nail", 1);
insert into image values ("needle.png", "needle", 2);
insert into image values ("onion.png", "onion", 2);
insert into image values ("orange.png", "orange", 3);
insert into image values ("owl.png", "owl", 1);
insert into image values ("pan.png", "pan", 1);
insert into image values ("pants.png", "pants", 2);
insert into image values ("pea.png", "pea", 1);
insert into image values ("peacock.png", "peacock", 3);
insert into image values ("pear.png", "pear", 1);
insert into image values ("pen.png", "pen", 1);
insert into image values ("pencil.png", "pencil", 2);
insert into image values ("pig.png", "pig", 1);
insert into image values ("pin.png", "pin", 1);
insert into image values ("plane.png", "plane", 2);
insert into image values ("potato.png", "potato", 2);
insert into image values ("pots.png", "pots", 1);
insert into image values ("rainboots.png", "rainboots", 3);
insert into image values ("rhino.png", "rhino", 2);
insert into image values ("rocket.png", "rocket", 2);
insert into image values ("rooster.png", "rooster", 3);
insert into image values ("rope.png", "rope", 1);
insert into image values ("scarf.png", "scarf", 2);
insert into image values ("schoolbus.png", "schoolbus", 3);
insert into image values ("scissors.png", "scissors", 3);
insert into image values ("scooter.png", "scooter", 3);
insert into image values ("screw.png", "screw", 2);
insert into image values ("seagull.png", "seagull", 3);
insert into image values ("sheep.png", "sheep", 2);
insert into image values ("ship.png", "ship", 1);
insert into image values ("shirt.png", "shirt", 2);
insert into image values ("sled.png", "sled", 1);
insert into image values ("snail.png", "snail", 2);
insert into image values ("snake.png", "snake", 2);
insert into image values ("sneakers.png", "sneakers", 3);
insert into image values ("sofa.png", "sofa", 1);
insert into image values ("spider.png", "spider", 2);
insert into image values ("sponge.png", "sponge", 2);
insert into image values ("squirrel.png", "squirrel", 3);
insert into image values ("stamp.png", "stamp", 2);
insert into image values ("star.png", "star", 1);
insert into image values ("stoplight.png", "stoplight", 3);
insert into image values ("store.png", "store", 2);
insert into image values ("strawberry.png", "strawberry", 3);
insert into image values ("street.png", "street", 2);
insert into image values ("suitcase.png", "suitcase", 3);
insert into image values ("sun.png", "sun", 1);
insert into image values ("swan.png", "swan", 1);
insert into image values ("swing.png", "swing", 2);
insert into image values ("table.png", "table", 2);
insert into image values ("thumb.png", "thumb", 2);
insert into image values ("ticket.png", "ticket", 3);
insert into image values ("tiger.png", "tiger", 2);
insert into image values ("tomato.png", "tomato", 2);
insert into image values ("tooth.png", "tooth", 2);
insert into image values ("train.png", "train", 2);
insert into image values ("tree.png", "tree", 1);
insert into image values ("trumpet.png", "trumpet", 3);
insert into image values ("ufo.png", "ufo", 1);
insert into image values ("umbrella.png", "umbrella", 3);
insert into image values ("whale.png", "whale", 2);
insert into image values ("wolf.png", "wolf", 2);
insert into image values ("yarn.png", "yarn", 1);
insert into image values ("zebra.png", "zebra", 2);


insert into hands values ("a", 4);
insert into hands values ("s", 4);
insert into hands values ("d", 4);
insert into hands values ("f", 4);
insert into hands values ("as", 4);
insert into hands values ("ad", 4);
insert into hands values ("af", 4);
insert into hands values ("asd", 4);
insert into hands values ("asf", 4);
insert into hands values ("asdf", 4);
insert into hands values ("aaddss", 4);
insert into hands values ("aassdd", 4);
insert into hands values ("aaddff", 4);
insert into hands values ("adfs", 4);
insert into hands values ("adfsd", 4);
insert into hands values ("adfs", 4);
insert into hands values ("asdd", 4);
insert into hands values ("adfds", 4);
insert into hands values ("afdds", 4);
insert into hands values ("adfsdf", 4);
insert into hands values ("adfada", 4);
insert into hands values ("aaff", 4);
insert into hands values ("aaddfff", 4);
insert into hands values ("affddssdfdd", 4);
insert into hands values ("affadddad", 4);
insert into hands values ("affasddd", 4);
insert into hands values ("affsddsdd", 4);
insert into hands values ("aadsddsdsd", 4);
insert into hands values ("asdsssds", 4);
insert into hands values ("add", 4);
insert into hands values ("aff", 4);
insert into hands values ("addf", 4);
insert into hands values ("affdd", 4);
insert into hands values ("affs", 4);
insert into hands values ("asdd", 4);
insert into hands values ("adsdd", 4);
insert into hands values ("addssff", 4);
insert into hands values ("afddff", 4);
insert into hands values ("assdda", 4);
insert into hands values ("affssdd", 4);
insert into hands values ("aaaddss", 4);
insert into hands values ("aaddffaa", 4);
insert into hands values ("aaddssff", 4);
insert into hands values ("aaddffss", 4);
insert into hands values ("sd", 4);
insert into hands values ("sa", 4);
insert into hands values ("sf", 4);
insert into hands values ("ssd", 4);
insert into hands values ("ssf", 4);
insert into hands values ("ssa", 4);
insert into hands values ("ssfd", 4);
insert into hands values ("ssaf", 4);
insert into hands values ("ssafd", 4);
insert into hands values ("ssfdaf", 4);
insert into hands values ("sfasdd", 4);
insert into hands values ("sfss", 4);
insert into hands values ("sdaf", 4);
insert into hands values ("sfdas", 4);
insert into hands values ("ssdsa", 4);
insert into hands values ("sdfa", 4);
insert into hands values ("sddss", 4);
insert into hands values ("sdssas", 4);
insert into hands values ("ssdass", 4);
insert into hands values ("asdddda", 4);
insert into hands values ("sdds", 4);
insert into hands values ("ssdaf", 4);
insert into hands values ("ssddss", 4);
insert into hands values ("ssffss", 4);
insert into hands values ("ssaaff", 4);
insert into hands values ("ssaaff", 4);
insert into hands values ("ssddffaa", 4);
insert into hands values ("sdafs", 4);
insert into hands values ("adfsdf", 4);
insert into hands values ("sdafsd", 4);
insert into hands values ("sdadsds", 4);
insert into hands values ("sdsssda", 4);
insert into hands values ("sdfadsds", 4);
insert into hands values ("ssdddafaff", 4);
insert into hands values ("dd", 4);
insert into hands values ("da", 4);
insert into hands values ("df", 4);
insert into hands values ("dsf", 4);
insert into hands values ("daf", 4);
insert into hands values ("dfs", 4);
insert into hands values ("dasd", 4);
insert into hands values ("ddss", 4);
insert into hands values ("ddff", 4);
insert into hands values ("dss", 4);
insert into hands values ("daas", 4);
insert into hands values ("ddssaa", 4);
insert into hands values ("ddffss", 4);
insert into hands values ("ddss", 4);
insert into hands values ("ddssdd", 4);
insert into hands values ("dddd", 4);
insert into hands values ("ddssaadd", 4);
insert into hands values ("ddssaa", 4);
insert into hands values ("dddssaa", 4);
insert into hands values ("ddssddss", 4);
insert into hands values ("ddssadd", 4);
insert into hands values ("dsdas", 4);
insert into hands values ("dsfasd", 4);
insert into hands values ("dsdas", 4);
insert into hands values ("ddssddd", 4);
insert into hands values ("ddffss", 4);
insert into hands values ("dasdsd", 4);
insert into hands values ("ddffss", 4);
insert into hands values ("ddssddas", 4);
insert into hands values ("ddss", 4);
insert into hands values ("dffdfd", 4);
insert into hands values ("dadadd", 4);
insert into hands values ("dsdsdddss", 4);
insert into hands values ("ddfss", 4);
insert into hands values ("ddssaa", 4);
insert into hands values ("dddss", 4);
insert into hands values ("ddssaa", 4);
insert into hands values ("ddssdd", 4);
insert into hands values ("ddadd", 4);
insert into hands values ("dassa", 4);
insert into hands values ("dsfaaa", 4);
insert into hands values ("dfsdads", 4);
insert into hands values ("dsfas", 4);
insert into hands values ("dfsdads", 4);
insert into hands values ("dsafs", 4);
insert into hands values ("dasdss", 4);
insert into hands values ("dfsd", 4);
insert into hands values ("dddfss", 4);
insert into hands values ("dafsd", 4);
insert into hands values ("ff", 4);
insert into hands values ("fs", 4);
insert into hands values ("fd", 4);
insert into hands values ("fa", 4);
insert into hands values ("fdf", 4);
insert into hands values ("fsf", 4);
insert into hands values ("fff", 4);
insert into hands values ("fdsf", 4);
insert into hands values ("fasdf", 4);
insert into hands values ("fdsdd", 4);
insert into hands values ("fasdsf", 4);
insert into hands values ("fdffd", 4);
insert into hands values ("fdsddd", 4);
insert into hands values ("fsddas", 4);
insert into hands values ("ffdsa", 4);
insert into hands values ("fdsdf", 4);
insert into hands values ("ffsdd", 4);
insert into hands values ("ffss", 4);
insert into hands values ("fsdff", 4);
insert into hands values ("fasdss", 4);
insert into hands values ("fsddd", 4);
insert into hands values ("fsdds", 4);
insert into hands values ("fafssdssd", 4);
insert into hands values ("fasdsd", 4);
insert into hands values ("fddds", 4);
insert into hands values ("faddss", 4);
insert into hands values ("fdsdsd", 4);
insert into hands values ("ffdss", 4);
insert into hands values ("ffadd", 4);
insert into hands values ("ffssdd", 4);
insert into hands values ("ffaadd", 4);
insert into hands values ("ffssdd", 4);
insert into hands values ("ffaaff", 4);
insert into hands values ("ffddff", 4);
insert into hands values ("ffssaa", 4);
insert into hands values ("fffffasd", 4);
insert into hands values ("ffad", 4);
insert into hands values ("fffadfa", 4);
insert into hands values ("ffddfdff", 4);
insert into hands values ("ffddaasddd", 4);
insert into hands values ("fddadfds", 4);
insert into hands values ("fddfafds", 4);
insert into hands values ("ffssdd", 4);
insert into hands values ("ffaafffff", 4);
insert into hands values ("fffaaddd", 4);
insert into hands values ("ffssdd", 4);
insert into hands values ("fffdddssssaaa", 4);
insert into hands values ("j", 5);
insert into hands values ("k", 5);
insert into hands values ("l", 5);
insert into hands values ("jj", 5);
insert into hands values ("kk", 5);
insert into hands values ("jkk", 5);
insert into hands values ("jllkj", 5);
insert into hands values ("jkjlj", 5);
insert into hands values ("jkkj", 5);
insert into hands values ("jjjk", 5);
insert into hands values ("jjjl", 5);
insert into hands values ("jjjkk", 5);
insert into hands values ("jjjll", 5);
insert into hands values ("jllk", 5);
insert into hands values ("jlkklkl", 5);
insert into hands values ("jklkj", 5);
insert into hands values ("jkjljkj", 5);
insert into hands values ("jjjk", 5);
insert into hands values ("jjjj", 5);
insert into hands values ("jjjkkjj", 5);
insert into hands values ("jjklll", 5);
insert into hands values ("jjklk", 5);
insert into hands values ("jkkll", 5);
insert into hands values ("jkkjljlll", 5);
insert into hands values ("jjkk", 5);
insert into hands values ("jkkjj", 5);
insert into hands values ("jkkll", 5);
insert into hands values ("jjkkll", 5);
insert into hands values ("jjjkk", 5);
insert into hands values ("jjjllkk", 5);
insert into hands values ("jlkljkk", 5);
insert into hands values ("jkljkl", 5);
insert into hands values ("jkjkj", 5);
insert into hands values ("jjkk", 5);
insert into hands values ("jjjkll", 5);
insert into hands values ("jkjjkk", 5);
insert into hands values ("jjjll", 5);
insert into hands values ("jkkjj", 5);
insert into hands values ("jjjkkll", 5);
insert into hands values ("jjkj", 5);
insert into hands values ("jlklj", 5);
insert into hands values ("jjjl", 5);
insert into hands values ("jlkk", 5);
insert into hands values ("l", 5);
insert into hands values ("lkk", 5);
insert into hands values ("lll", 5);
insert into hands values ("ll", 5);
insert into hands values ("lljkk", 5);
insert into hands values ("llklj", 5);
insert into hands values ("llkl", 5);
insert into hands values ("llljl", 5);
insert into hands values ("lj", 5);
insert into hands values ("lllj", 5);
insert into hands values ("llj", 5);
insert into hands values ("llk", 5);
insert into hands values ("llkj", 5);
insert into hands values ("lljk", 5);
insert into hands values ("lllkk", 5);
insert into hands values ("lllkkj", 5);
insert into hands values ("llljjk", 5);
insert into hands values ("llljj", 5);
insert into hands values ("lllkkj", 5);
insert into hands values ("llljjkj", 5);
insert into hands values ("ljkllklk", 5);
insert into hands values ("ljklll", 5);
insert into hands values ("lklkjj", 5);
insert into hands values ("lllkkjj", 5);
insert into hands values ("ljjkkll", 5);
insert into hands values ("lllkkjj", 5);
insert into hands values ("ljjkk", 5);
insert into hands values ("llljjkkk", 5);
insert into hands values ("llljjkkk", 5);
insert into hands values ("lllkkj", 5);
insert into hands values ("llljjj", 5);
insert into hands values ("ljklllk", 5);
insert into hands values ("ljkllk", 5);
insert into hands values ("lllkkjj", 5);
insert into hands values ("ljjkkll", 5);
insert into hands values ("lllkkjj", 5);
insert into hands values ("lllkkjjj", 5);
insert into hands values ("lklkkll", 5);
insert into hands values ("ljllll", 5);
insert into hands values ("lllklj", 5);
insert into hands values ("lljkjlkj", 5);
insert into hands values ("lllkj", 5);
insert into hands values ("lllkkjj", 5);
insert into hands values ("llklljjl", 5);
insert into hands values ("lljjl", 5);
insert into hands values ("ljlljjj", 5);
insert into hands values ("lllklk", 5);
insert into hands values ("ljllllk", 5);
insert into hands values ("llkjlkljl", 5);
insert into hands values ("llkjlkk", 5);
insert into hands values ("llljjjjj", 5);
insert into hands values ("llkklllll", 5);
insert into hands values ("llljjjjk", 5);
insert into hands values ("llljjjjjjj", 5);
insert into hands values ("lllllljjjjj", 5);
insert into hands values ("llljkjjkj", 5);
insert into hands values ("llklklklkl", 5);
insert into hands values ("llljjjj", 5);
insert into hands values ("lklk", 5);
insert into hands values ("llklk", 5);
insert into hands values ("k", 5);
insert into hands values ("kk", 5);
insert into hands values ("klj", 5);
insert into hands values ("kkj", 5);
insert into hands values ("kllk", 5);
insert into hands values ("kkjk", 5);
insert into hands values ("klkl", 5);
insert into hands values ("kkjkj", 5);
insert into hands values ("kkjkjj", 5);
insert into hands values ("kklk", 5);
insert into hands values ("klkkl", 5);
insert into hands values ("kjj", 5);
insert into hands values ("kllj", 5);
insert into hands values ("kkkjjk", 5);
insert into hands values ("klkklk", 5);
insert into hands values ("kjkkjj", 5);
insert into hands values ("kll", 5);
insert into hands values ("kjj", 5);
insert into hands values ("kkkkk", 5);
insert into hands values ("kllkkk", 5);
insert into hands values ("kjjkj", 5);
insert into hands values ("kkkllk", 5);
insert into hands values ("kj", 5);
insert into hands values ("kkj", 5);
insert into hands values ("kl", 5);
insert into hands values ("kll", 5);
insert into hands values ("kklll", 5);
insert into hands values ("klll", 5);
insert into hands values ("kkjkk", 5);
insert into hands values ("kjjkk", 5);
insert into hands values ("klllkk", 5);
insert into hands values ("klkk", 5);
insert into hands values ("kjjkkjjkkk", 5);
insert into hands values ("kllkkjjkk", 5);
insert into hands values ("kllkkll", 5);
insert into hands values ("kkkjlll", 5);
insert into hands values ("kkklljj", 5);
insert into hands values ("kljkkll", 5);
insert into hands values ("kkkjjll", 5);
insert into hands values ("klljjkk", 5);
insert into hands values ("kllkkjjkk", 5);
insert into hands values ("kkkjjlllkk", 5);
insert into hands values ("klkjklkjkl", 5);
insert into hands values ("kklkkkjjkk", 5);
insert into hands values ("kjkjkjk", 5);
insert into hands values ("klkljk", 5);
insert into hands values ("kllkk", 5);
insert into hands values ("kjkjll", 5);
insert into hands values ("kklljk", 5);
insert into hands values ("kkklljj", 5);
insert into hands values ("klkjkjlkj", 5);
insert into hands values ("kllkk", 5);
insert into hands values ("kjkjj", 5);
insert into hands values ("klkllkkk", 5);
insert into hands values ("klkjk", 5);
insert into hands values ("kjk", 5);
insert into hands values ("klklk", 5);
insert into hands values ("kkjlkj", 5);
insert into hands values ("kklkl", 5);
insert into hands values ("kkkkkkkkkk", 5);
insert into hands values ("kjkjkjl", 5);
insert into hands values ("klkjmlkjlkj", 5);
insert into hands values ("kkjlk", 5);
insert into hands values ("kllkk", 5);
insert into hands values ("kllk", 5);
insert into hands values ("kjjkk", 5);
insert into hands values ("kljkj", 5);
insert into hands values ("kkkjj", 5);
insert into hands values ("klklkjl", 5);
insert into hands values ("kkjll", 5);
insert into hands values ("kkkjkk", 5);
insert into hands values ("klkjl", 5);








